-- Fase 3.4 - Conciliacao avancada e workflow por espelho de custo

CREATE TABLE IF NOT EXISTS cost_mirror_reconciliations (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  cost_mirror_id BIGINT UNSIGNED NOT NULL,
  person_id BIGINT UNSIGNED NOT NULL,
  reference_month DATE NOT NULL,
  compared_at DATETIME NOT NULL,
  compared_by BIGINT UNSIGNED NULL,
  divergences_total INT UNSIGNED NOT NULL DEFAULT 0,
  high_severity_total INT UNSIGNED NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'pendente',
  lock_editing TINYINT(1) NOT NULL DEFAULT 0,
  approval_notes TEXT NULL,
  approved_by BIGINT UNSIGNED NULL,
  approved_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uq_cost_mirror_reconciliations_mirror (cost_mirror_id),
  KEY idx_cost_mirror_reconciliations_person (person_id),
  KEY idx_cost_mirror_reconciliations_reference_month (reference_month),
  KEY idx_cost_mirror_reconciliations_status (status),
  KEY idx_cost_mirror_reconciliations_lock (lock_editing),
  KEY idx_cost_mirror_reconciliations_compared_by (compared_by),
  KEY idx_cost_mirror_reconciliations_approved_by (approved_by),
  KEY idx_cost_mirror_reconciliations_deleted_at (deleted_at),
  CONSTRAINT fk_cost_mirror_reconciliations_mirror FOREIGN KEY (cost_mirror_id) REFERENCES cost_mirrors(id) ON DELETE CASCADE,
  CONSTRAINT fk_cost_mirror_reconciliations_person FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE CASCADE,
  CONSTRAINT fk_cost_mirror_reconciliations_compared_by FOREIGN KEY (compared_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_cost_mirror_reconciliations_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cost_mirror_divergences (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  reconciliation_id BIGINT UNSIGNED NOT NULL,
  cost_mirror_id BIGINT UNSIGNED NOT NULL,
  person_id BIGINT UNSIGNED NOT NULL,
  cost_plan_item_id BIGINT UNSIGNED NULL,
  mirror_item_id BIGINT UNSIGNED NULL,
  match_key VARCHAR(190) NOT NULL,
  divergence_type VARCHAR(40) NOT NULL,
  severity VARCHAR(20) NOT NULL,
  expected_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  actual_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  difference_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  threshold_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  requires_justification TINYINT(1) NOT NULL DEFAULT 0,
  justification_text TEXT NULL,
  justification_by BIGINT UNSIGNED NULL,
  justified_at DATETIME NULL,
  is_resolved TINYINT(1) NOT NULL DEFAULT 0,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  KEY idx_cost_mirror_divergences_reconciliation (reconciliation_id),
  KEY idx_cost_mirror_divergences_mirror (cost_mirror_id),
  KEY idx_cost_mirror_divergences_person (person_id),
  KEY idx_cost_mirror_divergences_type (divergence_type),
  KEY idx_cost_mirror_divergences_severity (severity),
  KEY idx_cost_mirror_divergences_requires_justification (requires_justification),
  KEY idx_cost_mirror_divergences_is_resolved (is_resolved),
  KEY idx_cost_mirror_divergences_justification_by (justification_by),
  KEY idx_cost_mirror_divergences_created_by (created_by),
  KEY idx_cost_mirror_divergences_deleted_at (deleted_at),
  CONSTRAINT fk_cost_mirror_divergences_reconciliation FOREIGN KEY (reconciliation_id) REFERENCES cost_mirror_reconciliations(id) ON DELETE CASCADE,
  CONSTRAINT fk_cost_mirror_divergences_mirror FOREIGN KEY (cost_mirror_id) REFERENCES cost_mirrors(id) ON DELETE CASCADE,
  CONSTRAINT fk_cost_mirror_divergences_person FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE CASCADE,
  CONSTRAINT fk_cost_mirror_divergences_plan_item FOREIGN KEY (cost_plan_item_id) REFERENCES cost_plan_items(id) ON DELETE SET NULL,
  CONSTRAINT fk_cost_mirror_divergences_mirror_item FOREIGN KEY (mirror_item_id) REFERENCES cost_mirror_items(id) ON DELETE SET NULL,
  CONSTRAINT fk_cost_mirror_divergences_justification_by FOREIGN KEY (justification_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_cost_mirror_divergences_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
