-- Fase 9.5 - Central de pendencias (documentos, divergencias, retornos)

CREATE TABLE IF NOT EXISTS analyst_pending_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  person_id BIGINT UNSIGNED NOT NULL,
  assignment_id BIGINT UNSIGNED NULL,
  pending_type VARCHAR(20) NOT NULL,
  source_key VARCHAR(140) NOT NULL,
  title VARCHAR(190) NOT NULL,
  description VARCHAR(255) NULL,
  severity VARCHAR(20) NOT NULL DEFAULT 'media',
  status VARCHAR(20) NOT NULL DEFAULT 'aberta',
  due_date DATE NULL,
  assigned_user_id BIGINT UNSIGNED NULL,
  metadata LONGTEXT NULL,
  resolved_at DATETIME NULL,
  resolved_by BIGINT UNSIGNED NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uq_analyst_pending_items_source (person_id, pending_type, source_key),
  KEY idx_analyst_pending_items_status_type (status, pending_type, severity, updated_at),
  KEY idx_analyst_pending_items_assignment (assignment_id, status, deleted_at),
  KEY idx_analyst_pending_items_person (person_id, status, deleted_at),
  KEY idx_analyst_pending_items_assigned (assigned_user_id, status, deleted_at),
  KEY idx_analyst_pending_items_resolved_by (resolved_by),
  KEY idx_analyst_pending_items_created_by (created_by),
  CONSTRAINT fk_analyst_pending_items_person FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE CASCADE,
  CONSTRAINT fk_analyst_pending_items_assignment FOREIGN KEY (assignment_id) REFERENCES assignments(id) ON DELETE SET NULL,
  CONSTRAINT fk_analyst_pending_items_assigned_user FOREIGN KEY (assigned_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_analyst_pending_items_resolved_by FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_analyst_pending_items_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
