-- Fase 9.19 - Evolucao assistida por IA (extracao, inconsistencias e sugestoes)

CREATE TABLE IF NOT EXISTS document_ai_reviews (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  person_id BIGINT UNSIGNED NOT NULL,
  trigger_source VARCHAR(30) NOT NULL DEFAULT 'manual',
  status VARCHAR(20) NOT NULL DEFAULT 'concluido',
  documents_total INT UNSIGNED NOT NULL DEFAULT 0,
  extractions_total INT UNSIGNED NOT NULL DEFAULT 0,
  inconsistencies_total INT UNSIGNED NOT NULL DEFAULT 0,
  suggestions_total INT UNSIGNED NOT NULL DEFAULT 0,
  summary LONGTEXT NULL,
  executed_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  KEY idx_document_ai_reviews_person (person_id, created_at),
  KEY idx_document_ai_reviews_status (status, created_at),
  KEY idx_document_ai_reviews_executed_by (executed_by),
  KEY idx_document_ai_reviews_deleted_at (deleted_at),
  CONSTRAINT fk_document_ai_reviews_person FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE CASCADE,
  CONSTRAINT fk_document_ai_reviews_executed_by FOREIGN KEY (executed_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS document_ai_extractions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  review_id BIGINT UNSIGNED NOT NULL,
  person_id BIGINT UNSIGNED NOT NULL,
  document_id BIGINT UNSIGNED NOT NULL,
  source_scope VARCHAR(30) NOT NULL DEFAULT 'metadata',
  extracted_sei VARCHAR(120) NULL,
  extracted_cpf VARCHAR(14) NULL,
  extracted_competence DATE NULL,
  extracted_amount DECIMAL(12,2) NULL,
  confidence_score DECIMAL(5,2) NOT NULL DEFAULT 0,
  raw_excerpt TEXT NULL,
  extracted_payload LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uq_document_ai_extractions_review_document (review_id, document_id),
  KEY idx_document_ai_extractions_person (person_id, created_at),
  KEY idx_document_ai_extractions_document (document_id),
  KEY idx_document_ai_extractions_competence (extracted_competence),
  KEY idx_document_ai_extractions_amount (extracted_amount),
  KEY idx_document_ai_extractions_deleted_at (deleted_at),
  CONSTRAINT fk_document_ai_extractions_review FOREIGN KEY (review_id) REFERENCES document_ai_reviews(id) ON DELETE CASCADE,
  CONSTRAINT fk_document_ai_extractions_person FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE CASCADE,
  CONSTRAINT fk_document_ai_extractions_document FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS document_ai_findings (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  review_id BIGINT UNSIGNED NOT NULL,
  person_id BIGINT UNSIGNED NOT NULL,
  document_id BIGINT UNSIGNED NULL,
  divergence_id BIGINT UNSIGNED NULL,
  finding_type VARCHAR(30) NOT NULL,
  rule_key VARCHAR(80) NOT NULL,
  severity VARCHAR(20) NOT NULL DEFAULT 'media',
  status VARCHAR(20) NOT NULL DEFAULT 'aberta',
  title VARCHAR(190) NOT NULL,
  description TEXT NULL,
  suggested_justification TEXT NULL,
  confidence_score DECIMAL(5,2) NOT NULL DEFAULT 0,
  metadata LONGTEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  resolved_by BIGINT UNSIGNED NULL,
  resolved_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  KEY idx_document_ai_findings_review (review_id, finding_type, severity),
  KEY idx_document_ai_findings_person (person_id, status, created_at),
  KEY idx_document_ai_findings_document (document_id),
  KEY idx_document_ai_findings_divergence (divergence_id),
  KEY idx_document_ai_findings_rule (rule_key),
  KEY idx_document_ai_findings_created_by (created_by),
  KEY idx_document_ai_findings_resolved_by (resolved_by),
  KEY idx_document_ai_findings_deleted_at (deleted_at),
  CONSTRAINT fk_document_ai_findings_review FOREIGN KEY (review_id) REFERENCES document_ai_reviews(id) ON DELETE CASCADE,
  CONSTRAINT fk_document_ai_findings_person FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE CASCADE,
  CONSTRAINT fk_document_ai_findings_document FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE SET NULL,
  CONSTRAINT fk_document_ai_findings_divergence FOREIGN KEY (divergence_id) REFERENCES cost_mirror_divergences(id) ON DELETE SET NULL,
  CONSTRAINT fk_document_ai_findings_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_document_ai_findings_resolved_by FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
