<?php

declare(strict_types=1);

use App\Controllers\AuthController;
use App\Controllers\BudgetController;
use App\Controllers\CdosController;
use App\Controllers\CostMirrorReconciliationController;
use App\Controllers\CostMirrorsController;
use App\Controllers\CostItemsController;
use App\Controllers\DashboardController;
use App\Controllers\DocumentTypesController;
use App\Controllers\GlobalSearchController;
use App\Controllers\HealthController;
use App\Controllers\InvoicesController;
use App\Controllers\LgpdController;
use App\Controllers\MteDestinationsController;
use App\Controllers\OfficeTemplatesController;
use App\Controllers\OrgansController;
use App\Controllers\OpsHealthPanelController;
use App\Controllers\PendingCenterController;
use App\Controllers\PeopleController;
use App\Controllers\PipelineFlowsController;
use App\Controllers\ProcessMetadataController;
use App\Controllers\ReportsController;
use App\Controllers\SecurityController;
use App\Controllers\SlaAlertsController;
use App\Controllers\UsersController;

$app = app();
$router = $app->router();

$router->get('/health', [HealthController::class, 'index']);

$router->get('/login', [AuthController::class, 'showLogin'], ['guest']);
$router->post('/login', [AuthController::class, 'login'], ['guest', 'csrf']);
$router->post('/logout', [AuthController::class, 'logout'], ['auth', 'csrf']);
$router->get('/users/password', [UsersController::class, 'passwordForm'], ['auth']);
$router->post('/users/password/update', [UsersController::class, 'updateOwnPassword'], ['auth', 'csrf']);

$router->get('/', [DashboardController::class, 'index'], ['auth', 'permission:dashboard.view']);
$router->get('/dashboard', [DashboardController::class, 'index'], ['auth', 'permission:dashboard.view']);
$router->get('/dashboard2', [DashboardController::class, 'legacy'], ['auth', 'permission:dashboard.view']);
$router->get('/global-search', [GlobalSearchController::class, 'index'], ['auth', 'permission:people.view']);
$router->get('/users', [UsersController::class, 'index'], ['auth', 'permission:users.view']);
$router->get('/users/create', [UsersController::class, 'create'], ['auth', 'permission:users.manage']);
$router->post('/users/store', [UsersController::class, 'store'], ['auth', 'permission:users.manage', 'csrf']);
$router->get('/users/show', [UsersController::class, 'show'], ['auth', 'permission:users.view']);
$router->get('/users/edit', [UsersController::class, 'edit'], ['auth', 'permission:users.manage']);
$router->post('/users/update', [UsersController::class, 'update'], ['auth', 'permission:users.manage', 'csrf']);
$router->post('/users/delete', [UsersController::class, 'destroy'], ['auth', 'permission:users.manage', 'csrf']);
$router->post('/users/toggle-active', [UsersController::class, 'toggleActive'], ['auth', 'permission:users.manage', 'csrf']);
$router->get('/users/roles', [UsersController::class, 'roles'], ['auth', 'permission:users.manage']);
$router->post('/users/roles/update', [UsersController::class, 'updateRolePermissions'], ['auth', 'permission:users.manage', 'csrf']);
$router->post('/users/reset-password', [UsersController::class, 'resetPassword'], ['auth', 'permission:users.manage', 'csrf']);
$router->get('/lgpd', [LgpdController::class, 'index'], ['auth', 'permission:lgpd.view']);
$router->get('/lgpd/export/access-csv', [LgpdController::class, 'exportAccessCsv'], ['auth', 'permission:lgpd.view']);
$router->post('/lgpd/policies/upsert', [LgpdController::class, 'upsertPolicy'], ['auth', 'permission:lgpd.manage', 'csrf']);
$router->post('/lgpd/retention/run', [LgpdController::class, 'runRetention'], ['auth', 'permission:lgpd.manage', 'csrf']);
$router->get('/security', [SecurityController::class, 'index'], ['auth', 'permission:security.view']);
$router->post('/security/update', [SecurityController::class, 'update'], ['auth', 'permission:security.manage', 'csrf']);
$router->get('/ops/health-panel', [OpsHealthPanelController::class, 'index'], ['auth', 'permission:security.view']);
$router->get('/budget', [BudgetController::class, 'index'], ['auth', 'permission:budget.view']);
$router->post('/budget/simulate', [BudgetController::class, 'simulate'], ['auth', 'permission:budget.simulate', 'csrf']);
$router->post('/budget/cycles/store', [BudgetController::class, 'storeCycle'], ['auth', 'permission:budget.manage', 'csrf']);
$router->post('/budget/cycles/update', [BudgetController::class, 'updateCycle'], ['auth', 'permission:budget.manage', 'csrf']);
$router->post('/budget/cycles/delete', [BudgetController::class, 'destroyCycle'], ['auth', 'permission:budget.manage', 'csrf']);
$router->post('/budget/scenario-parameters/upsert', [BudgetController::class, 'upsertScenarioParameter'], ['auth', 'permission:budget.manage', 'csrf']);
$router->get('/cdos', [CdosController::class, 'index'], ['auth', 'permission:cdo.view']);
$router->get('/cdos/create', [CdosController::class, 'create'], ['auth', 'permission:cdo.manage']);
$router->post('/cdos/store', [CdosController::class, 'store'], ['auth', 'permission:cdo.manage', 'csrf']);
$router->get('/cdos/show', [CdosController::class, 'show'], ['auth', 'permission:cdo.view']);
$router->get('/cdos/edit', [CdosController::class, 'edit'], ['auth', 'permission:cdo.manage']);
$router->post('/cdos/update', [CdosController::class, 'update'], ['auth', 'permission:cdo.manage', 'csrf']);
$router->post('/cdos/delete', [CdosController::class, 'destroy'], ['auth', 'permission:cdo.manage', 'csrf']);
$router->post('/cdos/people/link', [CdosController::class, 'linkPerson'], ['auth', 'permission:cdo.manage', 'csrf']);
$router->post('/cdos/people/unlink', [CdosController::class, 'unlinkPerson'], ['auth', 'permission:cdo.manage', 'csrf']);
$router->get('/invoices', [InvoicesController::class, 'index'], ['auth', 'permission:invoice.view']);
$router->get('/invoices/create', [InvoicesController::class, 'create'], ['auth', 'permission:invoice.manage']);
$router->post('/invoices/store', [InvoicesController::class, 'store'], ['auth', 'permission:invoice.manage', 'csrf']);
$router->get('/invoices/show', [InvoicesController::class, 'show'], ['auth', 'permission:invoice.view']);
$router->get('/invoices/edit', [InvoicesController::class, 'edit'], ['auth', 'permission:invoice.manage']);
$router->post('/invoices/update', [InvoicesController::class, 'update'], ['auth', 'permission:invoice.manage', 'csrf']);
$router->post('/invoices/delete', [InvoicesController::class, 'destroy'], ['auth', 'permission:invoice.manage', 'csrf']);
$router->post('/invoices/people/link', [InvoicesController::class, 'linkPerson'], ['auth', 'permission:invoice.manage', 'csrf']);
$router->post('/invoices/people/unlink', [InvoicesController::class, 'unlinkPerson'], ['auth', 'permission:invoice.manage', 'csrf']);
$router->post('/invoices/payments/store', [InvoicesController::class, 'storePayment'], ['auth', 'permission:invoice.manage', 'csrf']);
$router->get('/invoices/payments/proof', [InvoicesController::class, 'downloadPaymentProof'], ['auth', 'permission:invoice.view']);
$router->get('/invoices/pdf', [InvoicesController::class, 'downloadPdf'], ['auth', 'permission:invoice.view']);
$router->get('/invoices/payment-batches', [InvoicesController::class, 'paymentBatches'], ['auth', 'permission:invoice.view']);
$router->get('/invoices/payment-batches/show', [InvoicesController::class, 'showPaymentBatch'], ['auth', 'permission:invoice.view']);
$router->post('/invoices/payment-batches/store', [InvoicesController::class, 'storePaymentBatch'], ['auth', 'permission:invoice.manage', 'csrf']);
$router->post('/invoices/payment-batches/final-approval/simulate', [InvoicesController::class, 'simulatePaymentBatchFinalApproval'], ['auth', 'permission:invoice.manage', 'csrf']);
$router->post('/invoices/payment-batches/status/update', [InvoicesController::class, 'updatePaymentBatchStatus'], ['auth', 'permission:invoice.manage', 'csrf']);
$router->get('/cost-mirrors', [CostMirrorsController::class, 'index'], ['auth', 'permission:cost_mirror.view']);
$router->get('/cost-mirrors/create', [CostMirrorsController::class, 'create'], ['auth', 'permission:cost_mirror.manage']);
$router->post('/cost-mirrors/store', [CostMirrorsController::class, 'store'], ['auth', 'permission:cost_mirror.manage', 'csrf']);
$router->get('/cost-mirrors/show', [CostMirrorsController::class, 'show'], ['auth', 'permission:cost_mirror.view']);
$router->get('/cost-mirrors/edit', [CostMirrorsController::class, 'edit'], ['auth', 'permission:cost_mirror.manage']);
$router->post('/cost-mirrors/update', [CostMirrorsController::class, 'update'], ['auth', 'permission:cost_mirror.manage', 'csrf']);
$router->post('/cost-mirrors/delete', [CostMirrorsController::class, 'destroy'], ['auth', 'permission:cost_mirror.manage', 'csrf']);
$router->post('/cost-mirrors/items/store', [CostMirrorsController::class, 'storeItem'], ['auth', 'permission:cost_mirror.manage', 'csrf']);
$router->post('/cost-mirrors/items/import-csv', [CostMirrorsController::class, 'importCsv'], ['auth', 'permission:cost_mirror.manage', 'csrf']);
$router->post('/cost-mirrors/items/delete', [CostMirrorsController::class, 'destroyItem'], ['auth', 'permission:cost_mirror.manage', 'csrf']);
$router->get('/cost-mirrors/reconciliation/show', [CostMirrorReconciliationController::class, 'show'], ['auth', 'permission:cost_mirror.view']);
$router->post('/cost-mirrors/reconciliation/run', [CostMirrorReconciliationController::class, 'run'], ['auth', 'permission:cost_mirror.manage', 'csrf']);
$router->post('/cost-mirrors/reconciliation/justify', [CostMirrorReconciliationController::class, 'justify'], ['auth', 'permission:cost_mirror.manage', 'csrf']);
$router->post('/cost-mirrors/reconciliation/approve', [CostMirrorReconciliationController::class, 'approve'], ['auth', 'permission:cost_mirror.manage', 'csrf']);
$router->get('/office-templates', [OfficeTemplatesController::class, 'index'], ['auth', 'permission:office_template.view']);
$router->get('/office-templates/create', [OfficeTemplatesController::class, 'create'], ['auth', 'permission:office_template.manage']);
$router->post('/office-templates/store', [OfficeTemplatesController::class, 'store'], ['auth', 'permission:office_template.manage', 'csrf']);
$router->get('/office-templates/show', [OfficeTemplatesController::class, 'show'], ['auth', 'permission:office_template.view']);
$router->get('/office-templates/edit', [OfficeTemplatesController::class, 'edit'], ['auth', 'permission:office_template.manage']);
$router->post('/office-templates/update', [OfficeTemplatesController::class, 'update'], ['auth', 'permission:office_template.manage', 'csrf']);
$router->post('/office-templates/delete', [OfficeTemplatesController::class, 'destroy'], ['auth', 'permission:office_template.manage', 'csrf']);
$router->post('/office-templates/version/create', [OfficeTemplatesController::class, 'createVersion'], ['auth', 'permission:office_template.manage', 'csrf']);
$router->post('/office-templates/generate', [OfficeTemplatesController::class, 'generate'], ['auth', 'permission:office_template.manage', 'csrf']);
$router->get('/office-documents/show', [OfficeTemplatesController::class, 'showDocument'], ['auth', 'permission:office_template.view']);
$router->get('/office-documents/print', [OfficeTemplatesController::class, 'printDocument'], ['auth', 'permission:office_template.view']);
$router->get('/office-documents/pdf', [OfficeTemplatesController::class, 'downloadDocumentPdf'], ['auth', 'permission:office_template.view']);
$router->get('/process-meta', [ProcessMetadataController::class, 'index'], ['auth', 'permission:process_meta.view']);
$router->get('/process-meta/create', [ProcessMetadataController::class, 'create'], ['auth', 'permission:process_meta.manage']);
$router->post('/process-meta/store', [ProcessMetadataController::class, 'store'], ['auth', 'permission:process_meta.manage', 'csrf']);
$router->get('/process-meta/show', [ProcessMetadataController::class, 'show'], ['auth', 'permission:process_meta.view']);
$router->get('/process-meta/edit', [ProcessMetadataController::class, 'edit'], ['auth', 'permission:process_meta.manage']);
$router->post('/process-meta/update', [ProcessMetadataController::class, 'update'], ['auth', 'permission:process_meta.manage', 'csrf']);
$router->post('/process-meta/delete', [ProcessMetadataController::class, 'destroy'], ['auth', 'permission:process_meta.manage', 'csrf']);
$router->get('/process-meta/dou-attachment', [ProcessMetadataController::class, 'downloadDouAttachment'], ['auth', 'permission:process_meta.view']);
$router->get('/sla-alerts', [SlaAlertsController::class, 'index'], ['auth', 'permission:sla.view']);
$router->get('/sla-alerts/rules', [SlaAlertsController::class, 'rules'], ['auth', 'permission:sla.manage']);
$router->post('/sla-alerts/rules/upsert', [SlaAlertsController::class, 'upsertRule'], ['auth', 'permission:sla.manage', 'csrf']);
$router->post('/sla-alerts/dispatch-email', [SlaAlertsController::class, 'dispatchEmail'], ['auth', 'permission:sla.manage', 'csrf']);
$router->post('/sla-alerts/control/update', [SlaAlertsController::class, 'updateControl'], ['auth', 'permission:sla.manage', 'csrf']);
$router->get('/reports', [ReportsController::class, 'index'], ['auth', 'permission:report.view']);
$router->get('/reports/export/csv', [ReportsController::class, 'exportCsv'], ['auth', 'permission:report.view']);
$router->get('/reports/export/pdf', [ReportsController::class, 'exportPdf'], ['auth', 'permission:report.view']);
$router->get('/reports/export/zip', [ReportsController::class, 'exportZip'], ['auth', 'permission:report.view']);
$router->get('/reports/export/audit-zip', [ReportsController::class, 'exportAuditZip'], ['auth', 'permission:report.view']);
$router->get('/people', [PeopleController::class, 'index'], ['auth', 'permission:people.view']);
$router->get('/people/create', [PeopleController::class, 'create'], ['auth', 'permission:people.manage']);
$router->post('/people/store', [PeopleController::class, 'store'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/people/import-csv', [PeopleController::class, 'importCsv'], ['auth', 'permission:people.manage', 'csrf']);
$router->get('/people/show', [PeopleController::class, 'show'], ['auth', 'permission:people.view']);
$router->get('/people/pending', [PendingCenterController::class, 'index'], ['auth', 'permission:people.view']);
$router->post('/people/pending/status', [PendingCenterController::class, 'updateStatus'], ['auth', 'permission:people.manage', 'csrf']);
$router->get('/people/edit', [PeopleController::class, 'edit'], ['auth', 'permission:people.manage']);
$router->post('/people/update', [PeopleController::class, 'update'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/people/delete', [PeopleController::class, 'destroy'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/people/pipeline/advance', [PeopleController::class, 'advancePipeline'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/people/pipeline/queue/update', [PeopleController::class, 'updatePipelineQueue'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/people/pipeline/checklist/update', [PeopleController::class, 'updatePipelineChecklist'], ['auth', 'permission:people.manage', 'csrf']);
$router->get('/pipeline-flows', [PipelineFlowsController::class, 'index'], ['auth', 'permission:people.manage']);
$router->get('/pipeline-flows/create', [PipelineFlowsController::class, 'create'], ['auth', 'permission:people.manage']);
$router->post('/pipeline-flows/store', [PipelineFlowsController::class, 'store'], ['auth', 'permission:people.manage', 'csrf']);
$router->get('/pipeline-flows/show', [PipelineFlowsController::class, 'show'], ['auth', 'permission:people.manage']);
$router->get('/pipeline-flows/edit', [PipelineFlowsController::class, 'edit'], ['auth', 'permission:people.manage']);
$router->post('/pipeline-flows/update', [PipelineFlowsController::class, 'update'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/pipeline-flows/diagram/update', [PipelineFlowsController::class, 'updateDiagram'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/pipeline-flows/delete', [PipelineFlowsController::class, 'destroy'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/pipeline-flows/steps/upsert', [PipelineFlowsController::class, 'upsertStep'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/pipeline-flows/steps/delete', [PipelineFlowsController::class, 'deleteStep'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/pipeline-flows/transitions/upsert', [PipelineFlowsController::class, 'upsertTransition'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/pipeline-flows/transitions/delete', [PipelineFlowsController::class, 'deleteTransition'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/people/timeline/store', [PeopleController::class, 'storeTimelineEvent'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/people/timeline/rectify', [PeopleController::class, 'rectifyTimelineEvent'], ['auth', 'permission:people.manage', 'csrf']);
$router->get('/people/timeline/attachment', [PeopleController::class, 'downloadTimelineAttachment'], ['auth', 'permission:people.view']);
$router->get('/people/timeline/print', [PeopleController::class, 'timelinePrint'], ['auth', 'permission:people.view']);
$router->get('/document-types', [DocumentTypesController::class, 'index'], ['auth', 'permission:document_type.view']);
$router->get('/document-types/create', [DocumentTypesController::class, 'create'], ['auth', 'permission:document_type.manage']);
$router->post('/document-types/store', [DocumentTypesController::class, 'store'], ['auth', 'permission:document_type.manage', 'csrf']);
$router->get('/document-types/show', [DocumentTypesController::class, 'show'], ['auth', 'permission:document_type.view']);
$router->get('/document-types/edit', [DocumentTypesController::class, 'edit'], ['auth', 'permission:document_type.manage']);
$router->post('/document-types/update', [DocumentTypesController::class, 'update'], ['auth', 'permission:document_type.manage', 'csrf']);
$router->post('/document-types/toggle-active', [DocumentTypesController::class, 'toggleActive'], ['auth', 'permission:document_type.manage', 'csrf']);
$router->get('/cost-items', [CostItemsController::class, 'index'], ['auth', 'permission:cost_item.view']);
$router->get('/cost-items/create', [CostItemsController::class, 'create'], ['auth', 'permission:cost_item.manage']);
$router->post('/cost-items/store', [CostItemsController::class, 'store'], ['auth', 'permission:cost_item.manage', 'csrf']);
$router->get('/cost-items/show', [CostItemsController::class, 'show'], ['auth', 'permission:cost_item.view']);
$router->get('/cost-items/edit', [CostItemsController::class, 'edit'], ['auth', 'permission:cost_item.manage']);
$router->post('/cost-items/update', [CostItemsController::class, 'update'], ['auth', 'permission:cost_item.manage', 'csrf']);
$router->post('/cost-items/delete', [CostItemsController::class, 'destroy'], ['auth', 'permission:cost_item.manage', 'csrf']);
$router->post('/people/documents/store', [PeopleController::class, 'storeDocument'], ['auth', 'permission:people.manage', 'csrf']);
$router->get('/people/documents/download', [PeopleController::class, 'downloadDocument'], ['auth', 'permission:people.view']);
$router->post('/people/documents/version/store', [PeopleController::class, 'storeDocumentVersion'], ['auth', 'permission:people.manage', 'csrf']);
$router->get('/people/documents/version/download', [PeopleController::class, 'downloadDocumentVersion'], ['auth', 'permission:people.view']);
$router->post('/people/costs/version/create', [PeopleController::class, 'createCostVersion'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/people/costs/item/store', [PeopleController::class, 'storeCostItem'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/people/reimbursements/store', [PeopleController::class, 'storeReimbursement'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/people/reimbursements/mark-paid', [PeopleController::class, 'markReimbursementPaid'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/people/process-comments/store', [PeopleController::class, 'storeProcessComment'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/people/process-comments/update', [PeopleController::class, 'updateProcessComment'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/people/process-comments/delete', [PeopleController::class, 'deleteProcessComment'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/people/process-admin-timeline/store', [PeopleController::class, 'storeProcessAdminTimelineNote'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/people/process-admin-timeline/update', [PeopleController::class, 'updateProcessAdminTimelineNote'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/people/process-admin-timeline/delete', [PeopleController::class, 'deleteProcessAdminTimelineNote'], ['auth', 'permission:people.manage', 'csrf']);
$router->get('/people/audit/export', [PeopleController::class, 'exportAudit'], ['auth', 'permission:audit.view']);
$router->get('/people/dossier/export', [PeopleController::class, 'exportDossier'], ['auth', 'permission:people.view']);
$router->get('/mte-destinations', [MteDestinationsController::class, 'index'], ['auth', 'permission:mte_destinations.view']);
$router->get('/mte-destinations/create', [MteDestinationsController::class, 'create'], ['auth', 'permission:mte_destinations.manage']);
$router->post('/mte-destinations/store', [MteDestinationsController::class, 'store'], ['auth', 'permission:mte_destinations.manage', 'csrf']);
$router->get('/mte-destinations/show', [MteDestinationsController::class, 'show'], ['auth', 'permission:mte_destinations.view']);
$router->get('/mte-destinations/edit', [MteDestinationsController::class, 'edit'], ['auth', 'permission:mte_destinations.manage']);
$router->post('/mte-destinations/update', [MteDestinationsController::class, 'update'], ['auth', 'permission:mte_destinations.manage', 'csrf']);
$router->post('/mte-destinations/delete', [MteDestinationsController::class, 'destroy'], ['auth', 'permission:mte_destinations.manage', 'csrf']);
$router->get('/organs', [OrgansController::class, 'index'], ['auth', 'permission:organs.view']);
$router->get('/organs/create', [OrgansController::class, 'create'], ['auth', 'permission:organs.manage']);
$router->post('/organs/store', [OrgansController::class, 'store'], ['auth', 'permission:organs.manage', 'csrf']);
$router->post('/organs/import-csv', [OrgansController::class, 'importCsv'], ['auth', 'permission:organs.manage', 'csrf']);
$router->get('/organs/show', [OrgansController::class, 'show'], ['auth', 'permission:organs.view']);
$router->get('/organs/audit/export', [OrgansController::class, 'exportAudit'], ['auth', 'permission:audit.view']);
$router->get('/organs/edit', [OrgansController::class, 'edit'], ['auth', 'permission:organs.manage']);
$router->post('/organs/update', [OrgansController::class, 'update'], ['auth', 'permission:organs.manage', 'csrf']);
$router->post('/organs/delete', [OrgansController::class, 'destroy'], ['auth', 'permission:organs.manage', 'csrf']);
