<?php

declare(strict_types=1);

use App\Controllers\AuthController;
use App\Controllers\CdosController;
use App\Controllers\CostMirrorReconciliationController;
use App\Controllers\CostMirrorsController;
use App\Controllers\DashboardController;
use App\Controllers\HealthController;
use App\Controllers\InvoicesController;
use App\Controllers\OfficeTemplatesController;
use App\Controllers\OrgansController;
use App\Controllers\PeopleController;
use App\Controllers\ProcessMetadataController;
use App\Controllers\SlaAlertsController;

$app = app();
$router = $app->router();

$router->get('/health', [HealthController::class, 'index']);

$router->get('/login', [AuthController::class, 'showLogin'], ['guest']);
$router->post('/login', [AuthController::class, 'login'], ['guest', 'csrf']);
$router->post('/logout', [AuthController::class, 'logout'], ['auth', 'csrf']);

$router->get('/', [DashboardController::class, 'index'], ['auth', 'permission:dashboard.view']);
$router->get('/dashboard', [DashboardController::class, 'index'], ['auth', 'permission:dashboard.view']);
$router->get('/cdos', [CdosController::class, 'index'], ['auth', 'permission:cdo.view']);
$router->get('/cdos/create', [CdosController::class, 'create'], ['auth', 'permission:cdo.manage']);
$router->post('/cdos/store', [CdosController::class, 'store'], ['auth', 'permission:cdo.manage', 'csrf']);
$router->get('/cdos/show', [CdosController::class, 'show'], ['auth', 'permission:cdo.view']);
$router->get('/cdos/edit', [CdosController::class, 'edit'], ['auth', 'permission:cdo.manage']);
$router->post('/cdos/update', [CdosController::class, 'update'], ['auth', 'permission:cdo.manage', 'csrf']);
$router->post('/cdos/delete', [CdosController::class, 'destroy'], ['auth', 'permission:cdo.manage', 'csrf']);
$router->post('/cdos/people/link', [CdosController::class, 'linkPerson'], ['auth', 'permission:cdo.manage', 'csrf']);
$router->post('/cdos/people/unlink', [CdosController::class, 'unlinkPerson'], ['auth', 'permission:cdo.manage', 'csrf']);
$router->get('/invoices', [InvoicesController::class, 'index'], ['auth', 'permission:invoice.view']);
$router->get('/invoices/create', [InvoicesController::class, 'create'], ['auth', 'permission:invoice.manage']);
$router->post('/invoices/store', [InvoicesController::class, 'store'], ['auth', 'permission:invoice.manage', 'csrf']);
$router->get('/invoices/show', [InvoicesController::class, 'show'], ['auth', 'permission:invoice.view']);
$router->get('/invoices/edit', [InvoicesController::class, 'edit'], ['auth', 'permission:invoice.manage']);
$router->post('/invoices/update', [InvoicesController::class, 'update'], ['auth', 'permission:invoice.manage', 'csrf']);
$router->post('/invoices/delete', [InvoicesController::class, 'destroy'], ['auth', 'permission:invoice.manage', 'csrf']);
$router->post('/invoices/people/link', [InvoicesController::class, 'linkPerson'], ['auth', 'permission:invoice.manage', 'csrf']);
$router->post('/invoices/people/unlink', [InvoicesController::class, 'unlinkPerson'], ['auth', 'permission:invoice.manage', 'csrf']);
$router->post('/invoices/payments/store', [InvoicesController::class, 'storePayment'], ['auth', 'permission:invoice.manage', 'csrf']);
$router->get('/invoices/payments/proof', [InvoicesController::class, 'downloadPaymentProof'], ['auth', 'permission:invoice.view']);
$router->get('/invoices/pdf', [InvoicesController::class, 'downloadPdf'], ['auth', 'permission:invoice.view']);
$router->get('/cost-mirrors', [CostMirrorsController::class, 'index'], ['auth', 'permission:cost_mirror.view']);
$router->get('/cost-mirrors/create', [CostMirrorsController::class, 'create'], ['auth', 'permission:cost_mirror.manage']);
$router->post('/cost-mirrors/store', [CostMirrorsController::class, 'store'], ['auth', 'permission:cost_mirror.manage', 'csrf']);
$router->get('/cost-mirrors/show', [CostMirrorsController::class, 'show'], ['auth', 'permission:cost_mirror.view']);
$router->get('/cost-mirrors/edit', [CostMirrorsController::class, 'edit'], ['auth', 'permission:cost_mirror.manage']);
$router->post('/cost-mirrors/update', [CostMirrorsController::class, 'update'], ['auth', 'permission:cost_mirror.manage', 'csrf']);
$router->post('/cost-mirrors/delete', [CostMirrorsController::class, 'destroy'], ['auth', 'permission:cost_mirror.manage', 'csrf']);
$router->post('/cost-mirrors/items/store', [CostMirrorsController::class, 'storeItem'], ['auth', 'permission:cost_mirror.manage', 'csrf']);
$router->post('/cost-mirrors/items/import-csv', [CostMirrorsController::class, 'importCsv'], ['auth', 'permission:cost_mirror.manage', 'csrf']);
$router->post('/cost-mirrors/items/delete', [CostMirrorsController::class, 'destroyItem'], ['auth', 'permission:cost_mirror.manage', 'csrf']);
$router->get('/cost-mirrors/reconciliation/show', [CostMirrorReconciliationController::class, 'show'], ['auth', 'permission:cost_mirror.view']);
$router->post('/cost-mirrors/reconciliation/run', [CostMirrorReconciliationController::class, 'run'], ['auth', 'permission:cost_mirror.manage', 'csrf']);
$router->post('/cost-mirrors/reconciliation/justify', [CostMirrorReconciliationController::class, 'justify'], ['auth', 'permission:cost_mirror.manage', 'csrf']);
$router->post('/cost-mirrors/reconciliation/approve', [CostMirrorReconciliationController::class, 'approve'], ['auth', 'permission:cost_mirror.manage', 'csrf']);
$router->get('/office-templates', [OfficeTemplatesController::class, 'index'], ['auth', 'permission:office_template.view']);
$router->get('/office-templates/create', [OfficeTemplatesController::class, 'create'], ['auth', 'permission:office_template.manage']);
$router->post('/office-templates/store', [OfficeTemplatesController::class, 'store'], ['auth', 'permission:office_template.manage', 'csrf']);
$router->get('/office-templates/show', [OfficeTemplatesController::class, 'show'], ['auth', 'permission:office_template.view']);
$router->get('/office-templates/edit', [OfficeTemplatesController::class, 'edit'], ['auth', 'permission:office_template.manage']);
$router->post('/office-templates/update', [OfficeTemplatesController::class, 'update'], ['auth', 'permission:office_template.manage', 'csrf']);
$router->post('/office-templates/delete', [OfficeTemplatesController::class, 'destroy'], ['auth', 'permission:office_template.manage', 'csrf']);
$router->post('/office-templates/version/create', [OfficeTemplatesController::class, 'createVersion'], ['auth', 'permission:office_template.manage', 'csrf']);
$router->post('/office-templates/generate', [OfficeTemplatesController::class, 'generate'], ['auth', 'permission:office_template.manage', 'csrf']);
$router->get('/office-documents/show', [OfficeTemplatesController::class, 'showDocument'], ['auth', 'permission:office_template.view']);
$router->get('/office-documents/print', [OfficeTemplatesController::class, 'printDocument'], ['auth', 'permission:office_template.view']);
$router->get('/process-meta', [ProcessMetadataController::class, 'index'], ['auth', 'permission:process_meta.view']);
$router->get('/process-meta/create', [ProcessMetadataController::class, 'create'], ['auth', 'permission:process_meta.manage']);
$router->post('/process-meta/store', [ProcessMetadataController::class, 'store'], ['auth', 'permission:process_meta.manage', 'csrf']);
$router->get('/process-meta/show', [ProcessMetadataController::class, 'show'], ['auth', 'permission:process_meta.view']);
$router->get('/process-meta/edit', [ProcessMetadataController::class, 'edit'], ['auth', 'permission:process_meta.manage']);
$router->post('/process-meta/update', [ProcessMetadataController::class, 'update'], ['auth', 'permission:process_meta.manage', 'csrf']);
$router->post('/process-meta/delete', [ProcessMetadataController::class, 'destroy'], ['auth', 'permission:process_meta.manage', 'csrf']);
$router->get('/process-meta/dou-attachment', [ProcessMetadataController::class, 'downloadDouAttachment'], ['auth', 'permission:process_meta.view']);
$router->get('/sla-alerts', [SlaAlertsController::class, 'index'], ['auth', 'permission:sla.view']);
$router->get('/sla-alerts/rules', [SlaAlertsController::class, 'rules'], ['auth', 'permission:sla.manage']);
$router->post('/sla-alerts/rules/upsert', [SlaAlertsController::class, 'upsertRule'], ['auth', 'permission:sla.manage', 'csrf']);
$router->post('/sla-alerts/dispatch-email', [SlaAlertsController::class, 'dispatchEmail'], ['auth', 'permission:sla.manage', 'csrf']);
$router->get('/people', [PeopleController::class, 'index'], ['auth', 'permission:people.view']);
$router->get('/people/create', [PeopleController::class, 'create'], ['auth', 'permission:people.manage']);
$router->post('/people/store', [PeopleController::class, 'store'], ['auth', 'permission:people.manage', 'csrf']);
$router->get('/people/show', [PeopleController::class, 'show'], ['auth', 'permission:people.view']);
$router->get('/people/edit', [PeopleController::class, 'edit'], ['auth', 'permission:people.manage']);
$router->post('/people/update', [PeopleController::class, 'update'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/people/delete', [PeopleController::class, 'destroy'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/people/pipeline/advance', [PeopleController::class, 'advancePipeline'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/people/timeline/store', [PeopleController::class, 'storeTimelineEvent'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/people/timeline/rectify', [PeopleController::class, 'rectifyTimelineEvent'], ['auth', 'permission:people.manage', 'csrf']);
$router->get('/people/timeline/attachment', [PeopleController::class, 'downloadTimelineAttachment'], ['auth', 'permission:people.view']);
$router->get('/people/timeline/print', [PeopleController::class, 'timelinePrint'], ['auth', 'permission:people.view']);
$router->post('/people/documents/store', [PeopleController::class, 'storeDocument'], ['auth', 'permission:people.manage', 'csrf']);
$router->get('/people/documents/download', [PeopleController::class, 'downloadDocument'], ['auth', 'permission:people.view']);
$router->post('/people/costs/version/create', [PeopleController::class, 'createCostVersion'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/people/costs/item/store', [PeopleController::class, 'storeCostItem'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/people/reimbursements/store', [PeopleController::class, 'storeReimbursement'], ['auth', 'permission:people.manage', 'csrf']);
$router->post('/people/reimbursements/mark-paid', [PeopleController::class, 'markReimbursementPaid'], ['auth', 'permission:people.manage', 'csrf']);
$router->get('/people/audit/export', [PeopleController::class, 'exportAudit'], ['auth', 'permission:audit.view']);
$router->get('/organs', [OrgansController::class, 'index'], ['auth', 'permission:organs.view']);
$router->get('/organs/create', [OrgansController::class, 'create'], ['auth', 'permission:organs.manage']);
$router->post('/organs/store', [OrgansController::class, 'store'], ['auth', 'permission:organs.manage', 'csrf']);
$router->get('/organs/show', [OrgansController::class, 'show'], ['auth', 'permission:organs.view']);
$router->get('/organs/edit', [OrgansController::class, 'edit'], ['auth', 'permission:organs.manage']);
$router->post('/organs/update', [OrgansController::class, 'update'], ['auth', 'permission:organs.manage', 'csrf']);
$router->post('/organs/delete', [OrgansController::class, 'destroy'], ['auth', 'permission:organs.manage', 'csrf']);
